# Generated by Django 2.1.1 on 2018-09-12 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('merk', models.CharField(max_length=30)),
                ('gambar', models.ImageField(height_field=250, upload_to='', width_field=250)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=15)),
                ('qty', models.IntegerField(default=0)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produk.Kategori')),
            ],
        ),
    ]
