# Generated by Django 2.1.1 on 2018-09-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='gambar',
            field=models.ImageField(height_field='250', upload_to='', width_field='250'),
        ),
    ]
