# Generated by Django 2.1.1 on 2018-10-15 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produk', '0002_auto_20180914_0657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ongkir', models.DecimalField(decimal_places=2, max_digits=15)),
                ('alamat', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('qty', models.IntegerField(default=1)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('checkout', 'Checkout'), ('paid', 'Terbayar'), ('delivered', 'Terkirim')], default='checkout', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='produk',
            name='gambar',
            field=models.ImageField(blank=True, max_length=125, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='produk',
            name='merk',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='produk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produk.Produk'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
