# Generated by Django 2.1.1 on 2018-10-16 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0003_auto_20181015_0255'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harga', models.DecimalField(decimal_places=2, max_digits=15)),
                ('qty', models.IntegerField(default=1)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='produk',
        ),
        migrations.RemoveField(
            model_name='order',
            name='qty',
        ),
        migrations.AddField(
            model_name='order',
            name='no_hp',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='produk.Order'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='produk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produk.Produk'),
        ),
    ]
